name: Build
on: [push, pull_request]

jobs:
#  # Build job. Builds app for Android with Buildozer
#  build-android:
#    name: Build for Android
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Build with Buildozer
#        uses: ArtemSBulgakov/buildozer-action@v1
#        id: buildozer
#        with:
#          workdir: .
#          buildozer_version: stable
#
#      - name: Upload artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: package
#          path: ${{ steps.buildozer.outputs.filename }}

  build-ios:
    name: Build for iOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python3.11 -m pip install --upgrade pip virtualenv
          python3.11 -m venv venv
          source venv/bin/activate
  
          venv/bin/python3.11 -m pip install --upgrade kivy-ios buildozer
          venv/bin/python3.11 -m pip install --upgrade Cython==0.29.36 cookiecutter pbxproj
  
          brew install sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer automake cython

      - name: Build with buildozer
        run: |
          source venv/bin/activate
          venv/bin/python3.11 -m buildozer ios debug

      - name: LS
        run: |
          ls
          ls ./bin
