name: Build
on: [push, pull_request]

jobs:
  build-ios:
    name: Build for iOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python3.11 -m pip install --upgrade pip virtualenv
          python3.11 -m venv venv
          source venv/bin/activate

          venv/bin/python3.11 -m pip install --upgrade kivy-ios buildozer
          venv/bin/python3.11 -m pip install --upgrade Cython==0.29.36 cookiecutter pbxproj
          
          buildozer ios list_identities

          brew install sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer automake cython

      - name: Build with buildozer
        run: |
          source venv/bin/activate
          venv/bin/python3.11 -m buildozer ios debug

      - name: LS
        run: |
          ls
          ls ./bin

#  build-ios:
#    name: Build for iOS
#    runs-on: macos-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Install dependencies
#        run: |
#          python3.11 -m pip install --upgrade pip virtualenv
#
#          cd ..
#          python3.11 -m venv venv
#          source venv/bin/activate
#
#          venv/bin/python3.11 -m pip install --upgrade kivy==2.2.1 kivy-ios
#          venv/bin/python3.11 -m pip install --upgrade Cython==0.29.36
#
#          brew install sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer automake cython
#
#      - name: Build with buildozer
#        run: |
#          cd ..
#          source venv/bin/activate
#
#          toolchain build python3 --arch=arm64
#          toolchain build kivy --arch=arm64
#
#          toolchain create KivyIcons KivyIcons
#
#      - name: LS
#        run: |
#          cd ..
#          ls
#          ls kivyicons-ios

